### ISSUE TITLE
The program's entry point class 'com.amazonaws.kda.flink.starterkit.SessionProcessor' could not be loaded due to a linkage failure

### ISSUE THREAD

**Issue by phyyou** [aws-samples/amazon-kinesis-data-analytics-flink-starter-kit#12]
I created kinesis data analysis according to README.
However, the following error occurs:

```
org.apache.flink.client.program.ProgramInvocationException: The program's entry point class 'com.amazonaws.kda.flink.starterkit.SessionProcessor' could not be loaded due to a linkage failure. StackTrace: java.util.concurrent.CompletionException: org.apache.flink.client.program.ProgramInvocationException: The program's entry point class 'com.amazonaws.kda.flink.starterkit.SessionProcessor' could not be loaded due to a linkage failure.
at org.apache.flink.runtime.webmonitor.handlers.JarRunOverrideHandler.lambda$getJobGraphAsync$10(JarRunOverrideHandler.java:475)
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.flink.client.program.ProgramInvocationException: The program's entry point class 'com.amazonaws.kda.flink.starterkit.SessionProcessor' could not be loaded due to a linkage failure.
at org.apache.flink.client.program.PackagedProgram.loadMainClass(PackagedProgram.java:659)
at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:228)
at org.apache.flink.runtime.webmonitor.handlers.JarRunOverrideHandler.lambda$getJobGraphAsync$10(JarRunOverrideHandler.java:471)
... 4 more
Caused by: java.lang.UnsupportedClassVersionError: com/amazonaws/kda/flink/starterkit/SessionProcessor has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ChildFirstClassLoader.loadClass(FlinkUserCodeClassLoaders.java:130)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at org.apache.flink.client.program.PackagedProgram.loadMainClass(PackagedProgram.java:648)
... 6 more
```

![image](https://user-images.githubusercontent.com/34825352/161029305-87dc630a-35b6-4bb0-92ba-310fe637c598.png)

* target diretory: ![image](https://user-images.githubusercontent.com/34825352/161030319-2153e9bb-3c50-4683-a89a-ad7b06762ed6.png)
* build environment: ![image](https://user-images.githubusercontent.com/34825352/161030873-9f48915d-4674-4dce-862a-bed24e4ce2ed.png)

@itharavi
Can I start kinesis data analytics with this repository still now?

**Comment by itharavi** [comment]
Hi @phyyou - seems to be an issue with the JRE version you are using to run the application. Can you make sure the JRE version is similar or of higher version than the JRE used to build the Jar file?

Also, where are your running the application on? Local Flink installation or on Amazon Kinesis Data Analytics?

**Comment by phyyou** [comment]
Thanks. It could.
I tried to build this with an ec2 that 11 version JRE.
I close this issue.
